"""phishing analysis

Revision ID: 0002
Revises: 0001
"""

from alembic import op
import sqlalchemy as sa

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phishing_analysis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("sender", sa.String(length=320), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("rule_score", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("ml_probability", sa.Float(), nullable=True),
        sa.Column("ml_model_version", sa.String(length=64), nullable=True),
        sa.Column("ml_top_terms", sa.JSON(), nullable=True),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("link_count", sa.Integer(), nullable=False),
        sa.Column("attachment_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phishing_analysis_classification"),
        "phishing_analysis",
        ["classification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phishing_analysis_created_at"), "phishing_analysis", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_phishing_analysis_user_id"), "phishing_analysis", ["user_id"], unique=False
    )
    op.create_table(
        "phishing_indicators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["phishing_analysis.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phishing_indicators_analysis_id"),
        "phishing_indicators",
        ["analysis_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phishing_indicators_analysis_id"), table_name="phishing_indicators")
    op.drop_table("phishing_indicators")
    op.drop_index(op.f("ix_phishing_analysis_user_id"), table_name="phishing_analysis")
    op.drop_index(op.f("ix_phishing_analysis_created_at"), table_name="phishing_analysis")
    op.drop_index(op.f("ix_phishing_analysis_classification"), table_name="phishing_analysis")
    op.drop_table("phishing_analysis")
    # ### end Alembic commands ###
