"""threat intel cache

Revision ID: 0003
Revises: 0002
"""

from alembic import op
import sqlalchemy as sa

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threat_intel_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("indicator_type", sa.String(length=10), nullable=False),
        sa.Column("indicator_hash", sa.String(length=64), nullable=False),
        sa.Column("indicator", sa.Text(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "indicator_type", "indicator_hash", name="uq_intel_cache_key"
        ),
    )
    op.create_index(
        op.f("ix_threat_intel_cache_expires_at"), "threat_intel_cache", ["expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threat_intel_cache_expires_at"), table_name="threat_intel_cache")
    op.drop_table("threat_intel_cache")
    # ### end Alembic commands ###
