"""network sensors baselines findings

Revision ID: 0005
Revises: 0004
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('zeek', 'suricata', 'proxy', 'agent', 'other')", name='ck_sensors_kind'),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name='ck_sensors_latlng_pair'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('name')
    )
    op.create_table('network_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('detector', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['security_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['network_sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_findings_code'), 'network_findings', ['code'], unique=False)
    op.create_index(op.f('ix_network_findings_event_id'), 'network_findings', ['event_id'], unique=False)
    op.create_index(op.f('ix_network_findings_occurred_at'), 'network_findings', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_network_findings_sensor_id'), 'network_findings', ['sensor_id'], unique=False)
    op.create_table('tls_baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('cert_sha256', sa.String(length=64), nullable=True),
    sa.Column('max_tls_version', sa.String(length=8), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['network_sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sensor_id', 'server_name', name='uq_tls_baseline_host')
    )
    op.create_index(op.f('ix_tls_baselines_sensor_id'), 'tls_baselines', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tls_baselines_sensor_id'), table_name='tls_baselines')
    op.drop_table('tls_baselines')
    op.drop_index(op.f('ix_network_findings_sensor_id'), table_name='network_findings')
    op.drop_index(op.f('ix_network_findings_occurred_at'), table_name='network_findings')
    op.drop_index(op.f('ix_network_findings_event_id'), table_name='network_findings')
    op.drop_index(op.f('ix_network_findings_code'), table_name='network_findings')
    op.drop_table('network_findings')
    op.drop_table('network_sensors')
    # ### end Alembic commands ###
